services:
  database:
    container_name: bkeep_mysql
    image: mysql:9.1
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_bkeep
    ports:
      - "3306:3306"
    networks:
      - bkeep-api
    healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          timeout: 20s
          retries: 10
  web:
    container_name: bkeep_web
    image: bkeepapi/bkeep-api:0.0.1
    ports:
      - "80:80"
    networks:
      - bkeep-api
    depends_on:
      database:
        condition: service_healthy
    env_file: ".env"
  phpmyadmin:
    container_name: bkeep_phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - database
    ports:
      - "8080:80"
    environment:
      PMA_HOST: bkeep_mysql
      PMA_PORT: 3306
    networks:
      - bkeep-api
networks:
    bkeep-api: