name: Docker Image build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build Docker image and push to repositories
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: login to hub  
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: bkeepapi/bkeep-api:${{vars.VER}}
          
      - name: deploying
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker image pull bkeepapi/bkeep-api:$VER
            cd ~/bkeep-api
            git pull
            docker-compose -f compose-prod.yaml down
            docker-compose -f compose-prod.yaml up -d


